### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by T3kstiil3** [T3kstiil3/server-dashboard#2]
Add readme : 

- Add How to use : 
List all command in the package json
Explain the config/config.js file variable
- Display Screen 2 in screens directory

You can you inspire on : [teacher toolkit repo](https://github.com/T3kstiil3/teacher_toolkit)

**Comment by Avasse** [comment]
Hello, i'd be glad to work on this issue 😄

**Comment by T3kstiil3** [comment]
Great job 👍 @Avasse
